# fly.toml app configuration file generated for translation-service-nameless-haze-4636 on 2025-10-17T10:02:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'translation-service-nameless-haze-4636'
primary_region = 'fra'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
